apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: atividade
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: pod-1-container
      image: nginx:latest
      ports:
        - containerPort: 80