apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: atividade
  labels:
    app: segundo-pod
spec:
  containers:
    - name: pod-2-container
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: q1w2e3r4
        - name: "MYSQL_DATABASE"
          value: empresa
        - name: "MYSQL_PASSWORD"
          value: q1w2e3r4